## Getting started with TensorFlow 2.0

in this notebook we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* geting infromation from Tensors
* Manipulating Tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)

In [1]:
import tensorflow as tf

tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
# Create Tensors with tf.constant()
scalar=tf.constant(7)

scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
scalar.ndim  # it give the no of dimensions

0

In [7]:
# create a vector

vector=tf.constant([10,10])

vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vector.ndim

1

In [9]:
# create a matrix (has more than 1 dimension)

matrix=tf.constant([[10,7],[7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [18]:
another_matrix=tf.constant(
    [
        [27.,.5],
        [.5,27.]
    ],
    dtype=tf.float16
    ) # specify the data type with dtype parameters


In [19]:
another_matrix

<tf.Tensor: shape=(1, 2, 2), dtype=float16, numpy=
array([[[27. ,  0.5],
        [ 0.5, 27. ]]], dtype=float16)>

In [23]:
# create a Tensor

tensor=tf.constant([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]
])


tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

This is known as a rank 3 tensor (3-dimensions), however a tensor can have an arbitrary (unlimited) amount of dimensions.

For example, you might turn a series of images into tensors with shape (224, 224, 3, 32), where:

224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
3 is the number of colour channels of the image (red, green blue).
32 is the batch size (the number of images a neural network sees at any one time).
All of the above variables we've created are actually tensors. But you may also hear them referred to as their different names (the ones we gave them):

scalar: a single number.
vector: a number with direction (e.g. wind speed with direction).
matrix: a 2-dimensional array of numbers.
tensor: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).
To add to the confusion, the terms matrix and tensor are often used interchangably.

Going forward since we're using TensorFlow, everything we refer to and use will be tensors.

For more on the mathematical difference between scalars, vectors and matrices see the visual algebra post by Math is Fun.

difference between scalar, vector, matrix, tensor

![image](https://camo.githubusercontent.com/c389e3b3abc7e30e0e49b22a3899b349d8332d30e4d87c533f9ef71ee15c3da3/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d7264626f75726b652f74656e736f72666c6f772d646565702d6c6561726e696e672f6d61696e2f696d616765732f30302d7363616c61722d766563746f722d6d61747269782d74656e736f722e706e67)

Creating Tensors with tf.Variable()
You can also (although you likely rarely will, because often, when working with data, tensors are created for you automatically) create tensors using tf.Variable().

The difference between tf.Variable() and tf.constant() is tensors created with tf.constant() are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with tf.Variable() are mutable (can be changed).

In [31]:
changeable_tensor=tf.Variable([27,5])
unchangeable_tensor=tf.constant([27,5])

changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([27,  5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([27,  5], dtype=int32)>)

In [33]:
changeable_tensor[0].assign(11)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  5], dtype=int32)>

In [ ]:
# let try to change the unchangeable tensor

unchangeable_tensor[0].assign(11)

unchangeable_tensor # it will give error because it is constant

A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number).

> 🔑 Note: For now, you don't need to know too much about the different ranks of tensors (but we will see more on this later). The important point is knowing tensors can have an unlimited range of dimensions (the exact amount will depend on what data you're representing).

# Create random tensors

Random tensor are tensors of some abitrary size which contain random numbers

In [49]:
# create two random (but the same) tensors

random_1=tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1=random_1.normal(shape=(3,2))

# random 2

random_2=tf.random.Generator.from_seed(42)

random_2=random_2.normal(shape=(3,2))


# both are same ?

random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.75658023, -0.06854693],
        [ 0.07595028, -1.2573844 ],
        [-0.23193759, -1.8107857 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.75658023, -0.06854693],
        [ 0.07595028, -1.2573844 ],
        [-0.23193759, -1.8107857 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

#  shuffle the order of elements in a tensor

In [107]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect the learning)

not_shuffled=tf.constant([[20,7],[7,20],[27,5]])

not_shuffled.ndim


2

In [123]:

# shuffle our non-shuffled tensor
 
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled,seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20,  7],
       [ 7, 20],
       [27,  5]], dtype=int32)>

🛠 Exercise: Read through TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed:


> Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

In [133]:

# other way to make tensor

tf.ones([10,7]) # create tensor of all ones

tf.zeros([3,4]) # create tensor of all zeros



<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn NumPy arrays into tensors

the main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)


In [136]:
# turn numpy array into tensors

import numpy as np

numpy_A=np.arange(1,25,dtype=np.int32) # create a numpy array between 1 and 25

converted=tf.constant(numpy_A,shape=(2,3,4))

# 2*3*4=24 it means we can reshape it into 2*3*4
# if we want to reshape it into 2*3*5 then it will give error because 2*3*5=30



print(converted)

print("shape:",converted.shape)
print("dimension:",converted.ndim)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
shape: (2, 3, 4)
dimension: 3


In [152]:
converted.gpu() # check if tensor is running on GPU or not

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# Getting information from tensors

* Shape
* Rank
* Axis or dimension
* Size



In [153]:
# create rank 4 tensor (4 dimension)
rank_4_tensor=tf.zeros(shape=[2,3,4,5])

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [160]:
rank_4_tensor[0,1]  

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [162]:
print("shape:",rank_4_tensor.shape)
print("dimension:",rank_4_tensor.ndim)

# get various attributes of tensor

print("datatype of every element:",rank_4_tensor.dtype)

print("number of elements in our tensor:",tf.size(rank_4_tensor))


# indexing tensors

# get the first 2 elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

# get the first element from each dimension from each index except for the final one

rank_4_tensor[:1,:1,:1,:]


shape: (2, 3, 4, 5)
dimension: 4
datatype of every element: <dtype: 'float32'>
number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>