## Getting started with TensorFlow 2.0

in this notebook we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* geting infromation from Tensors
* Manipulating Tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)

In [13]:
import tensorflow as tf

tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [14]:
# Create Tensors with tf.constant()
scalar=tf.constant(7)

scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [15]:
scalar.ndim  # it give the no of dimensions

0

In [16]:
# create a vector

vector=tf.constant([10,10])

vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [17]:
vector.ndim

1

In [18]:
# create a matrix (has more than 1 dimension)

matrix=tf.constant([[10,7],[7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [19]:
another_matrix=tf.constant(
    [
        [27.,.5],
        [.5,27.]
    ],
    dtype=tf.float16
    ) # specify the data type with dtype parameters


In [20]:
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[27. ,  0.5],
       [ 0.5, 27. ]], dtype=float16)>

In [21]:
# create a Tensor

tensor=tf.constant([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]
])


tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

This is known as a rank 3 tensor (3-dimensions), however a tensor can have an arbitrary (unlimited) amount of dimensions.

For example, you might turn a series of images into tensors with shape (224, 224, 3, 32), where:

224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
3 is the number of colour channels of the image (red, green blue).
32 is the batch size (the number of images a neural network sees at any one time).
All of the above variables we've created are actually tensors. But you may also hear them referred to as their different names (the ones we gave them):

scalar: a single number.
vector: a number with direction (e.g. wind speed with direction).
matrix: a 2-dimensional array of numbers.
tensor: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).
To add to the confusion, the terms matrix and tensor are often used interchangably.

Going forward since we're using TensorFlow, everything we refer to and use will be tensors.

For more on the mathematical difference between scalars, vectors and matrices see the visual algebra post by Math is Fun.

difference between scalar, vector, matrix, tensor

![image](https://camo.githubusercontent.com/c389e3b3abc7e30e0e49b22a3899b349d8332d30e4d87c533f9ef71ee15c3da3/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d7264626f75726b652f74656e736f72666c6f772d646565702d6c6561726e696e672f6d61696e2f696d616765732f30302d7363616c61722d766563746f722d6d61747269782d74656e736f722e706e67)

Creating Tensors with tf.Variable()
You can also (although you likely rarely will, because often, when working with data, tensors are created for you automatically) create tensors using tf.Variable().

The difference between tf.Variable() and tf.constant() is tensors created with tf.constant() are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with tf.Variable() are mutable (can be changed).

In [22]:
changeable_tensor=tf.Variable([27,5])
unchangeable_tensor=tf.constant([27,5])

changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([27,  5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([27,  5], dtype=int32)>)

In [23]:
changeable_tensor[0].assign(11)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  5], dtype=int32)>

In [24]:
# let try to change the unchangeable tensor

unchangeable_tensor[0].assign(11)

unchangeable_tensor # it will give error because it is constant

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number).

> 🔑 Note: For now, you don't need to know too much about the different ranks of tensors (but we will see more on this later). The important point is knowing tensors can have an unlimited range of dimensions (the exact amount will depend on what data you're representing).

# Create random tensors

Random tensor are tensors of some abitrary size which contain random numbers

In [ ]:
# create two random (but the same) tensors

random_1=tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1=random_1.normal(shape=(3,2))

# random 2

random_2=tf.random.Generator.from_seed(42)

random_2=random_2.normal(shape=(3,2))


# both are same ?

random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.75658023, -0.06854693],
        [ 0.07595028, -1.2573844 ],
        [-0.23193759, -1.8107857 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.75658023, -0.06854693],
        [ 0.07595028, -1.2573844 ],
        [-0.23193759, -1.8107857 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

#  shuffle the order of elements in a tensor

In [ ]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't effect the learning)

not_shuffled=tf.constant([[20,7],[7,20],[27,5]])

not_shuffled.ndim


2

In [ ]:

# shuffle our non-shuffled tensor
 
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled,seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20,  7],
       [ 7, 20],
       [27,  5]], dtype=int32)>

🛠 Exercise: Read through TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.

It looks like if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seed:


> Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

In [ ]:

# other way to make tensor

tf.ones([10,7]) # create tensor of all ones

tf.zeros([3,4]) # create tensor of all zeros



<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn NumPy arrays into tensors

the main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)


In [ ]:
# turn numpy array into tensors

import numpy as np

numpy_A=np.arange(1,25,dtype=np.int32) # create a numpy array between 1 and 25

converted=tf.constant(numpy_A,shape=(2,3,4))

# 2*3*4=24 it means we can reshape it into 2*3*4
# if we want to reshape it into 2*3*5 then it will give error because 2*3*5=30



print(converted)

print("shape:",converted.shape)
print("dimension:",converted.ndim)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
shape: (2, 3, 4)
dimension: 3


In [ ]:
converted.gpu() # check if tensor is running on GPU or not

Instructions for updating:
Use tf.identity instead.


<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# Getting information from tensors

* Shape
* Rank
* Axis or dimension
* Size



In [ ]:
# create rank 4 tensor (4 dimension)
rank_4_tensor=tf.zeros(shape=[2,3,4,5])

rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0,1]  

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# get various attributes of our tensor

print("Datatyper of every element:",rank_4_tensor.dtype)

print("Number of dimensions (rank):",rank_4_tensor.ndim)

print("Shape of tensor:",rank_4_tensor.shape)

print("Elements along the 0 axis:",rank_4_tensor.shape[0])

print("Elements along the last axis:",rank_4_tensor.shape[-1])




Datatyper of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5


### indexing tensors

Tensors can be indexed just like Python lists 🥩

In [ ]:
# indexing tensors

# get the first 2 elements of each dimension

print("first Two Elements",rank_4_tensor[:2,:2,:2,:2])



first Two Elements tf.Tensor(
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]], shape=(2, 2, 2, 2), dtype=float32)


In [ ]:
# get the first element from each dimension from each index except for the final one

print("first element from each dimension from each index except for the final one",rank_4_tensor[:1,:1,:1,:])

first element from each dimension from each index except for the final one tf.Tensor([[[[0. 0. 0. 0. 0.]]]], shape=(1, 1, 1, 5), dtype=float32)


In [ ]:
# create a rank 2 tensor (2 dimension)
numpy_A=np.arange(1,7,dtype=np.int32) # create a numpy array between 1 and 25

rank_2_tensor=tf.constant(numpy_A,shape=(2,3))

rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
# get the last item of each of row of our rank 2 tensor

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor

rank_3_tensor=rank_2_tensor[...,tf.newaxis] # ... means all the axis before
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

In [ ]:
# alternative to tf.newaxis

tf.expand_dims(rank_2_tensor,axis=-1) # -1 means expand the final axis

# shape(2,3) when we expand the final axis then it become (2,3,1) [axis=-1]

# shape(2,3) when we expand the first axis then it become (1,2,3) [axis=0]


<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic Operations**

`+`,`-`,`*`,`/`



In [ ]:
tensor=tf.constant(([27,5],
                    [5,27]))

tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[37, 15],
       [15, 37]], dtype=int32)>

In [ ]:
# multiply tensor by 10

tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[270,  50],
       [ 50, 270]], dtype=int32)>

In [ ]:
# we can use the tensorflow built-in function too

tf.multiply(tensor,10)



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[270,  50],
       [ 50, 270]], dtype=int32)>

## Matrix multiplication in tensorflow
 

In machine learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors (or matrices) need to fulfil if we're going to matrix multiply them:

The inner dimensions must match
The resulting matrix has the shape of the outer dimensions



In [ ]:
# matrix multiplication in tensorflow

sample_tensor=tf.constant([[5,10],[10,5],[5,10]]) # shape(3,2)

# shape(3,2) * shape(2,3) = shape(3,3)
tf.matmul(sample_tensor,tf.transpose(sample_tensor)) # transpose of sample_tensor is shape(2,3)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[125, 100, 125],
       [100, 125, 100],
       [125, 100, 125]], dtype=int32)>

In [ ]:
# matrix multiplication with python operator "@"

sample_tensor @ sample_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[125, 100],
       [100, 125]], dtype=int32)>

**📖 Resource**: Info and example of matrix multiplication: https://www.mathsisfun.com/algebra/matrix-multiplying.html

The dot product

Matrix multiplication is also referrred to as the dot product.

You can perform matrix multiplication using:

* tf.matmul()
* tf.tensordot()
* @

for matrix multiplication the column of `first matrix` must be equal to row of `second matrix`

In [ ]:
# matrix multiplication with different Tensor

sample_tensor2=tf.constant([[5,10,5],[10,5,10],[5,10,5]]) # shape(3,3)

#  we cant multiply shape(3,2) * shape(3,3) because the inner dimension must match

sample_tensor2.shape,sample_tensor.shape

(TensorShape([3, 3]), TensorShape([2, 3]))

In [ ]:
# change the shape of sample_tensor

sample_tensor=tf.reshape(sample_tensor,shape=(2,3)) # two row and three column

tf.matmul(sample_tensor,sample_tensor2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[175, 200, 175],
       [125, 175, 125]], dtype=int32)>

**The Dot Product**

Matrix multiplication also refer as dot product

Matrxi multiplication can be performed:

* `tf.matmul()`
* `tf.tensordot()`



In [ ]:
tf.tensordot(sample_tensor,tf.transpose(sample_tensor2),axes=1) # axes=1 means multiply the inner dimension

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[175, 200, 175],
       [125, 175, 125]], dtype=int32)>

In [ ]:
# Transpose

print("Original Tensor:\n",sample_tensor)

print("----------")

print("Transpose Tensor:\n",tf.transpose(sample_tensor))


Original Tensor:
 tf.Tensor(
[[ 5 10 10]
 [ 5  5 10]], shape=(2, 3), dtype=int32)
----------
Transpose Tensor:
 tf.Tensor(
[[ 5  5]
 [10  5]
 [10 10]], shape=(3, 2), dtype=int32)


## Changing the datatype of the Tensor

16 bit is most faster than 32 bit but default type is in 32 buit ⛳

In [ ]:
# default datatype of tensor is  float32

float_tf=tf.constant([1.7,7.4])

int_tf=tf.constant([1,7])

float_tf.dtype,int_tf.dtype

(tf.float32, tf.int32)

In [ ]:
# change the datatype of tensor

float_tf=tf.cast(float_tf,dtype=tf.float16)

int_tf=tf.cast(int_tf,dtype=tf.int16)

float_tf.dtype,int_tf.dtype

(tf.float16, tf.int16)

## Aggregating Tensors

Aggregation can be done using various operations such as sum, mean, max, min, etc. The resulting tensor contains information from all the input tensors and can be used for further computations.


In [29]:
# get the absoulte value
aggregate_tensor=tf.constant([-27,-7])

tf.abs(aggregate_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([27,  7], dtype=int32)>

In [30]:
# Get Max in tensor
max_value = tf.reduce_max(aggregate_tensor)

# Get Min in tensor
min_value=tf.reduce_min(aggregate_tensor)

# Get mean
mean=tf.reduce_mean(aggregate_tensor)

# get sum

sum=tf.reduce_sum(aggregate_tensor)

print("The max value is ",max_value)

print("The min value is ",min_value)

print("The mean value is ",mean)

print("The sum value is ",sum)

The max value is  tf.Tensor(-7, shape=(), dtype=int32)
The min value is  tf.Tensor(-27, shape=(), dtype=int32)
The mean value is  tf.Tensor(-17, shape=(), dtype=int32)
The sum value is  tf.Tensor(-34, shape=(), dtype=int32)


**🛠️ E️xercise** : find the standart deviation and variance of the tensor `aggregate_tensor`

In [37]:

sd=tf.math.reduce_std(tf.cast(aggregate_tensor,dtype=tf.float32))

variance=tf.math.reduce_variance(tf.cast(aggregate_tensor,dtype=tf.float32))

print("The standard deviation is ",sd.numpy())

print("The variance is ",variance.numpy())

The standard deviation is  10.0
The variance is  100.0


##  Find the Positional maximum and minimum


In [56]:
tf.random.set_seed(42)

sample_tensor=tf.random.uniform(shape=[50],minval=0,maxval=10) 


In [57]:
tf.argmax(sample_tensor) # index of max value

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [58]:
tf.argmin(sample_tensor) # index of min value

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [60]:
# Index on our largest value position

sample_tensor[tf.argmax(sample_tensor)].numpy()

9.671384

In [63]:
# check its right or wrong

assert sample_tensor[tf.argmax(sample_tensor)]==tf.reduce_max(sample_tensor)

## Squeezing a tensor (removing all single dimensions)


In [67]:
tf.random.set_seed(42)

# Create a tensor with 50 values between 0 and 100
squeez_tensor= tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))

squeez_tensor


<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [68]:
squeez_tensor.shape

TensorShape([1, 1, 1, 1, 50])

In [78]:
G_squeezed=tf.squeeze(squeez_tensor)

tf.reduce_max(G_squeezed)



<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

# one-hot encoding

One-hot encoding is a technique used in machine learning and data preprocessing to convert categorical 
variables into a binary representation that can be used as input for machine learning algorithms.



In [88]:
radom_list=[0,1,2,3,4] # could be red,green,blue, alpha

one_hot_tensor=tf.one_hot(radom_list,depth=5,
                          on_value="I love deep learning",
                            off_value="I also like to dance",
                          )

one_hot_tensor

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance',
        b'I also like to dance'],
       [b'I also like to dance', b'I love deep learning',
        b'I also like to dance', b'I also like to dance',
        b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I love deep learning', b'I also like to dance',
        b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'I love deep learning',
        b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'I also like to dance',
        b'I love deep learning']], dtype=object)>

## Tensorflow and Numpy

Tensorflow interacts beautifully with NumPy arrays.

`np.array()` - pass a tensor to convert to an ndarray (NumPy's main datatype).

`tensor.numpy()` - call on a tensor to convert to an ndarray.
Doing this is helpful as it makes tensors iterable as well as allows us to use any of NumPy's methods on them.

In [91]:
import numpy as np
np_example=tf.constant(np.array([1,2,3]))

In [93]:
# convert our Tensor back to a NumPy array

np_example.numpy() # it will give error if we dont use tf.constant 


array([1, 2, 3])

In [94]:
# the default types of each are slightly different

numpy_J=tf.constant(np.array([3.,7.,10.])) # type float64

tensor_J=tf.constant([3.,7.,10.]) # type float32

numpy_J.dtype,tensor_J.dtype


(tf.float64, tf.float32)