## Getting started with TensorFlow 2.0

in this notebook we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* geting infromation from Tensors
* Manipulating Tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)

In [1]:
import tensorflow as tf

tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [5]:
# Create Tensors with tf.constant()
scalar=tf.constant(7)

scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
scalar.ndim  # it give the no of dimensions

0

In [7]:
# create a vector

vector=tf.constant([10,10])

vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vector.ndim

1

In [9]:
# create a matrix (has more than 1 dimension)

matrix=tf.constant([[10,7],[7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [18]:
another_matrix=tf.constant(
    [
        [27.,.5],
        [.5,27.]
    ],
    dtype=tf.float16
    ) # specify the data type with dtype parameters


In [19]:
another_matrix

<tf.Tensor: shape=(1, 2, 2), dtype=float16, numpy=
array([[[27. ,  0.5],
        [ 0.5, 27. ]]], dtype=float16)>

In [23]:
# create a Tensor

tensor=tf.constant([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ],
    [
        [13,14,15],
        [16,17,18]
    ]
])


tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

what we created so far:

* `scalar`: a single number
* `vector`: a number with direction (e.g. wind speed and direction)
* `matrix`: a 2-dimensional array of numbers
* `tensor`: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)


In [31]:
changeable_tensor=tf.Variable([27,5])
unchangeable_tensor=tf.constant([27,5])

changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([27,  5], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([27,  5], dtype=int32)>)

In [33]:
changeable_tensor[0].assign(11)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11,  5], dtype=int32)>

In [36]:
# let try to change the unchangeable tensor

unchangeable_tensor[0].assign(11)

unchangeable_tensor # it will give error because it is constant

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([27,  5], dtype=int32)>